
[functions.process-invoice]
enabled = true
verify_jwt = true
import_map = "./functions/process-invoice/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-invoice/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-invoice/*.html" ]

[functions.ask-my-invoices]
enabled = true
verify_jwt = true
import_map = "./functions/ask-my-invoices/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ask-my-invoices/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ask-my-invoices/*.html" ]

[functions.weebhook-mailgun]
enabled = true
verify_jwt = true
import_map = "./functions/weebhook-mailgun/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/weebhook-mailgun/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/weebhook-mailgun/*.html" ]

[functions.webhook-whatsapp]
enabled = true
verify_jwt = true
import_map = "./functions/webhook-whatsapp/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/webhook-whatsapp/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/webhook-whatsapp/*.html" ]

[functions.cotejo-inteligente]
enabled = true
verify_jwt = true
import_map = "./functions/cotejo-inteligente/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/cotejo-inteligente/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/cotejo-inteligente/*.html" ]

[functions.gestionar-sugerencias-cotejo]
enabled = true
verify_jwt = true
import_map = "./functions/gestionar-sugerencias-cotejo/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gestionar-sugerencias-cotejo/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gestionar-sugerencias-cotejo/*.html" ]
